### ISSUE TITLE
Project does not compile on gcc8.2

### ISSUE THREAD

**Issue by Serge-sudo** [intel/x86-simd-sort#196]
[1/8] Compiling C++ object lib/liblibicl.a.p/x86simdsort-icl.cpp.o
FAILED: lib/liblibicl.a.p/x86simdsort-icl.cpp.o 
c++ -Ilib/liblibicl.a.p -Ilib -I../lib -I../src -fvisibility=hidden -fvisibility-inlines-hidden -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Werror -std=c++17 -O3 -fPIC -march=icelake-client -MD -MQ lib/liblibicl.a.p/x86simdsort-icl.cpp.o -MF lib/liblibicl.a.p/x86simdsort-icl.cpp.o.d -o lib/liblibicl.a.p/x86simdsort-icl.cpp.o -c ../lib/x86simdsort-icl.cpp
In file included from ../src/x86simdsort-static-incl.h:167,
                 from ../lib/x86simdsort-icl.cpp:2:
../src/avx512-16bit-qsort.hpp: In static member function ‘static zmm_vector<float16>::reg_t zmm_vector<float16>::reverse(zmm_vector<float16>::reg_t)’:
../src/avx512-16bit-qsort.hpp:178:32: error: ‘_mm512_set_epi16’ was not declared in this scope
         const auto rev_index = _mm512_set_epi16(NETWORK_REVERSE_32LANES);
                                ^~~~~~~~~~~~~~~~
../src/avx512-16bit-qsort.hpp:178:32: note: suggested alternative: ‘_mm512_set1_epi16’
         const auto rev_index = _mm512_set_epi16(NETWORK_REVERSE_32LANES);
                                ^~~~~~~~~~~~~~~~
                                _mm512_set1_epi16
../src/avx512-16bit-qsort.hpp: In static member function ‘static zmm_vector<short int>::reg_t zmm_vector<short int>::reverse(zmm_vector<short int>::reg_t)’:
../src/avx512-16bit-qsort.hpp:323:32: error: ‘_mm512_set_epi16’ was not declared in this scope
         const auto rev_index = _mm512_set_epi16(NETWORK_REVERSE_32LANES);
                                ^~~~~~~~~~~~~~~~
../src/avx512-16bit-qsort.hpp:323:32: note: suggested alternative: ‘_mm512_set1_epi16’
         const auto rev_index = _mm512_set_epi16(NETWORK_REVERSE_32LANES);
                                ^~~~~~~~~~~~~~~~
                                _mm512_set1_epi16
../src/avx512-16bit-qsort.hpp: In static member function ‘static zmm_vector<short unsigned int>::reg_t zmm_vector<short unsigned int>::reverse(zmm_vector<short unsigned int>::reg_t)’:
../src/avx512-16bit-qsort.hpp:465:32: error: ‘_mm512_set_epi16’ was not declared in this scope
         const auto rev_index = _mm512_set_epi16(NETWORK_REVERSE_32LANES);
                                ^~~~~~~~~~~~~~~~
../src/avx512-16bit-qsort.hpp:465:32: note: suggested alternative: ‘_mm512_set1_epi16’
         const auto rev_index = _mm512_set_epi16(NETWORK_REVERSE_32LANES);
                                ^~~~~~~~~~~~~~~~
                                _mm512_set1_epi16
[4/8] Compiling C++ object lib/liblibavx.a.p/x86simdsort-avx2.cpp.o
ninja: build stopped: subcommand failed.

Getting this error when trying to compile project with gcc 8.2, although in documentation it states that is should compile just fine on 8.x
## Build requirements

The sorting routines relies only on the C++ Standard Library and requires a
relatively modern compiler to build (ex: gcc 8.x and above).

**Comment by r-devulap** [comment]
@Serge-sudo thanks for reporting the build fail. #198 fixes it.
